version: "3.9"

services:
  # Base image containing dependencies.
  openvino:
    image: ros2_humble_openvino_202203:latest
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        ROS_PRE_INSTALLED_PKG: humble-desktop
        VERSION: humble

    # Interactive shell
    stdin_open: true
    tty: true
    # Networking and IPC for ROS 2
    network_mode: host
    ipc: host
    # Needed to display graphical applications
    #privileged: true
    environment:
      # Allows graphical programs in the container.
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      # Allows graphical programs in the container.
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY:-$HOME/.Xauthority}:/root/.Xauthority
      - /dev:/dev
      - ./:/repo:rw